//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misaki.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MzQwODQ0NjE3NzA2NjM1Mjcz.DF4bzA.lmxxXUzpVzL-geBCQ84lc3nCSCg")]
        public string Token {
            get {
                return ((string)(this["Token"]));
            }
            set {
                this["Token"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H:\\Projects\\Bot\\Config\\")]
        public string ConfigDirectory {
            get {
                return ((string)(this["ConfigDirectory"]));
            }
            set {
                this["ConfigDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27ce8543aa8a418a04336ffb519c898e25e2b9b2")]
        public string OsuApiKey {
            get {
                return ((string)(this["OsuApiKey"]));
            }
            set {
                this["OsuApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H:\\Projects\\Bot\\Temp\\")]
        public string TempDirectory {
            get {
                return ((string)(this["TempDirectory"]));
            }
            set {
                this["TempDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wpck2vbZjN2A")]
        public string MALPassword {
            get {
                return ((string)(this["MALPassword"]));
            }
            set {
                this["MALPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ffmpeg-3.2.2-win64-static\\")]
        public string ffmpegPath {
            get {
                return ((string)(this["ffmpegPath"]));
            }
            set {
                this["ffmpegPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("112300152391294976")]
        public ulong HostingUserId {
            get {
                return ((ulong)(this["HostingUserId"]));
            }
            set {
                this["HostingUserId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\t8a9957dc0c88c59")]
        public string ImgurKey {
            get {
                return ((string)(this["ImgurKey"]));
            }
            set {
                this["ImgurKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("728eb23f3aaf0bdc72638a0bd62470ecd0dc5349")]
        public string ImgurSecret {
            get {
                return ((string)(this["ImgurSecret"]));
            }
            set {
                this["ImgurSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("03d0f9c6-e89b-4f84-8e63-2287dc35ed08")]
        public string PubgKey {
            get {
                return ((string)(this["PubgKey"]));
            }
            set {
                this["PubgKey"] = value;
            }
        }
    }
}
